<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

use Illuminate\Support\Carbon;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $password = Hash::make(123456789);
        $array = array(100, 200, 300);
        $users = [
            [
                'last_name' => "Admin",
                'first_name' => "Admin",
                'sex' => "Female",
                'email' => "admin@gmail.com",
                'email_prof' => "admin@digitrends.dev",
                'address' => "Bizerte",
                'date_birth' => '2004-01-01',
                'place_birth' => "Tunis",
                'status' => "active",
                'nationality' => "Tunisienne",
                'phone' => "+216 28 825 825",
                'phone_emergency' => "+216 28 825 855",
                'family_situation' => "Married",
                'nb_children' => 0,
                'level_studies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'registration' => "0",
                'carte_id' => null,
                'duration_sivp' => 0,
                'cin' => 11717895,
                'delivery_date_cin' => '2022-01-01',
                'delivery_place_cin' => "Bizerte",
                'num_passport' => "11177895",
                'registration' => "87a74-148l4",
                'integration_date' => '2022-10-31',
                'password' => $password,
                'motivation' => json_encode([["id" => 1, "text" => "environnement de travail"], ["id" => 3, "text" => "atmosphère"], ["id" => 2, "text" => "professionnalisme"], ["id" => 4, "text" => "Reconnaissance"], ["id" => 5, "text" => "argent"]]),

                'pwd_reset_admin' => 0,
                'email_verified_at' => null,
                'is_deleted' => 0,
                'regime_social' => "cnss",
                'text' => null,
                'image' => 'As5Z01669218048.png',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_name' => "Zaineb",
                'first_name' => "Zaineb",
                'sex' => "Female",
                'email' => "zaineb@gmail.com",
                'email_prof' => "zaineb@digitrends.dev",
                'address' => "Bizerte",
                'date_birth' => '2004-01-01',
                'place_birth' => "Tunis",
                'status' => "active",
                'nationality' => "Tunisien",
                'phone' => "+216 28 825 825",
                'phone_emergency' => "+216 28 825 855",
                'family_situation' => "Married",
                'nb_children' => 0,
                'level_studies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'registration' => "0",
                'carte_id' => null,
                'duration_sivp' => 0,
                'cin' => 11777895,
                'delivery_date_cin' => '2022-01-01',
                'delivery_place_cin' => "Bizerte",
                'num_passport' => "11777895",
                'registration' => "87a74-148l4",
                'integration_date' => '2022-10-31',
                'password' => $password,
                'motivation' => json_encode([["id" => 1, "text" => "environnement de travail"], ["id" => 3, "text" => "atmosphère"], ["id" => 2, "text" => "professionnalisme"], ["id" => 4, "text" => "Reconnaissance"], ["id" => 5, "text" => "argent"]]),

                'pwd_reset_admin' => 0,
                'email_verified_at' => null,
                'is_deleted' => 0,
                'regime_social' => "cnss",
                'text' => null,
                'image' => 'HOAuX1669218064.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_name' => "Selim",
                'first_name' => "Selim",
                'sex' => "Female",
                'email' => "selim@gmail.com",
                'email_prof' => "selim@digitrends.dev",
                'address' => "Bizerte",
                'date_birth' => '2004-01-01',
                'place_birth' => "Tunis",
                'status' => "active",
                'nationality' => "Tunisien",
                'phone' => "+216 55 825 825",
                'phone_emergency' => "+216 55 825 855",
                'family_situation' => "Married",
                'nb_children' => 0,
                'level_studies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'registration' => "0",
                'carte_id' => null,
                'duration_sivp' => 0,
                'cin' => 12545666,
                'delivery_date_cin' => '2022-01-01',
                'delivery_place_cin' => "Bizerte",
                'num_passport' => "12545666",
                'registration' => "696rrr-az78",
                'integration_date' => '2022-10-31',
                'password' => $password,
                'motivation' => json_encode([["id" => 1, "text" => "environnement de travail"], ["id" => 3, "text" => "atmosphère"], ["id" => 2, "text" => "professionnalisme"], ["id" => 4, "text" => "Reconnaissance"], ["id" => 5, "text" => "argent"]]),

                'pwd_reset_admin' => 0,
                'email_verified_at' => null,
                'is_deleted' => 0,
                'regime_social' => "cnss",
                'text' => null,
                'image' => 'Q58Kx1669218097.webp',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_name' => "Houcem",
                'first_name' => "Hedhly",
                'sex' => "male",
                'email' => "houcemH@gmail.com",
                'email_prof' => "houcemH@digitrends.dev",
                'address' => "Bizerte",
                'date_birth' => '2004-01-01',
                'place_birth' => "Tunis",
                'status' => "active",
                'nationality' => "Tunisien",
                'phone' => "+216 28 825 825",
                'phone_emergency' => "+216 28 825 855",
                'family_situation' => "Married",
                'nb_children' => 0,
                'level_studies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'registration' => "0",
                'carte_id' => null,
                'duration_sivp' => 0,
                'cin' => 11162526,
                'delivery_date_cin' => '2022-01-01',
                'delivery_place_cin' => "Bizerte",
                'num_passport' => "11277526",
                'registration' => "87a14-14aa4",
                'integration_date' => '2022-10-31',
                'password' => $password,
                'motivation' => json_encode([["id" => 1, "text" => "environnement de travail"], ["id" => 3, "text" => "atmosphère"], ["id" => 2, "text" => "professionnalisme"], ["id" => 4, "text" => "Reconnaissance"], ["id" => 5, "text" => "argent"]]),

                'pwd_reset_admin' => 0,
                'email_verified_at' => null,
                'is_deleted' => 0,
                'regime_social' => "cnss",
                'text' => null,
                'image' => 'img.png',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_name' => "Mohamed",
                'first_name' => "Mohamed",
                'sex' => "male",
                'email' => "mohamed@gmail.com",
                'email_prof' => "mohamed@digitrends.dev",
                'address' => "Bizerte",
                'date_birth' => '2004-01-01',
                'place_birth' => "Tunis",
                'status' => "active",
                'nationality' => "Tunisien",
                'phone' => "+216 25 825 825",
                'phone_emergency' => "+216 25 825 855",
                'family_situation' => "Single",
                'nb_children' => 0,
                'level_studies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'registration' => "0",
                'carte_id' => null,
                'duration_sivp' => 0,
                'cin' => 11111111,
                'delivery_date_cin' => '2022-01-01',
                'delivery_place_cin' => "Bizerte",
                'num_passport' => "11223344",
                'registration' => "12a58-8z4",
                'integration_date' => '2022-10-31',
                'password' => $password,
                'motivation' => json_encode([["id" => 1, "text" => "environnement de travail"], ["id" => 3, "text" => "atmosphère"], ["id" => 2, "text" => "professionnalisme"], ["id" => 4, "text" => "Reconnaissance"], ["id" => 5, "text" => "argent"]]),

                'pwd_reset_admin' => 0,
                'email_verified_at' => null,
                'is_deleted' => 0,
                'regime_social' => "cnss",
                'text' => null,
                'image' => 'img.png',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_name' => "Mourad",
                'first_name' => "Mourad",
                'sex' => "male",
                'email' => "mourad@gmail.com",
                'email_prof' => "mourad@digitrends.dev",
                'address' => "Bizerte",
                'date_birth' => '2004-01-01',
                'place_birth' => "Tunis",
                'status' => "active",
                'nationality' => "Tunisien",
                'phone' => "+216 28 825 825",
                'phone_emergency' => "+216 28 825 855",
                'family_situation' => "Married",
                'nb_children' => 0,
                'level_studies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'registration' => "0",
                'carte_id' => null,
                'duration_sivp' => 0,
                'cin' => 11772526,
                'delivery_date_cin' => '2022-01-01',
                'delivery_place_cin' => "Bizerte",
                'num_passport' => "11772526",
                'registration' => "87a94-14aa4",
                'integration_date' => '2022-10-31',
                'password' => $password,
                'motivation' => json_encode([["id" => 1, "text" => "environnement de travail"], ["id" => 3, "text" => "atmosphère"], ["id" => 2, "text" => "professionnalisme"], ["id" => 4, "text" => "Reconnaissance"], ["id" => 5, "text" => "argent"]]),

                'pwd_reset_admin' => 0,
                'email_verified_at' => null,
                'is_deleted' => 0,
                'regime_social' => "cnss",
                'text' => null,
                'image' => 'img.png',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_name' => "Mariem",
                'first_name' => "Mariem",
                'sex' => "Female",
                'email' => "mariem@gmail.com",
                'email_prof' => "mariem@digitrends.dev",
                'address' => "Bizerte",
                'date_birth' => '2004-01-01',
                'place_birth' => "Tunis",
                'status' => "active",
                'nationality' => "Tunisienne",
                'phone' => "+216 28 825 825",
                'phone_emergency' => "+216 28 825 855",
                'family_situation' => "Married",
                'nb_children' => 0,
                'level_studies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'registration' => "0",
                'carte_id' => null,
                'duration_sivp' => 0,
                'cin' => 11225665,
                'delivery_date_cin' => '2022-01-01',
                'delivery_place_cin' => "Bizerte",
                'num_passport' => "11225665",
                'registration' => "87a14-147",
                'integration_date' => '2022-10-31',
                'password' => $password,
                'motivation' => json_encode([["id" => 1, "text" => "environnement de travail"], ["id" => 3, "text" => "atmosphère"], ["id" => 2, "text" => "professionnalisme"], ["id" => 4, "text" => "Reconnaissance"], ["id" => 5, "text" => "argent"]]),

                'pwd_reset_admin' => 0,
                'email_verified_at' => null,
                'is_deleted' => 0,
                'regime_social' => "cnss",
                'text' => null,
                'image' => 'img.png',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_name' => "Nour",
                'first_name' => "Nour",
                'sex' => "Female",
                'email' => "nour@gmail.com",
                'email_prof' => "nour@digitrends.dev",
                'address' => "Bizerte",
                'date_birth' => '2004-01-01',
                'place_birth' => "Tunis",
                'status' => "active",
                'nationality' => "Tunisienne",
                'phone' => "+216 28 825 825",
                'phone_emergency' => "+216 28 825 855",
                'family_situation' => "Married",
                'nb_children' => 0,
                'level_studies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'registration' => "0",
                'carte_id' => null,
                'duration_sivp' => 0,
                'cin' => 15458566,
                'delivery_date_cin' => '2022-01-01',
                'delivery_place_cin' => "Bizerte",
                'num_passport' => "85528599",
                'registration' => "87a14-14777",
                'integration_date' => '2022-10-31',
                'password' => $password,
                'motivation' => json_encode([["id" => 1, "text" => "environnement de travail"], ["id" => 3, "text" => "atmosphère"], ["id" => 2, "text" => "professionnalisme"], ["id" => 4, "text" => "Reconnaissance"], ["id" => 5, "text" => "argent"]]),
                'pwd_reset_admin' => 0,
                'email_verified_at' => null,
                'is_deleted' => 0,
                'regime_social' => "cnss",
                'text' => null,
                'image' => 'img.png',
                'created_at' => now(),
                'updated_at' => now()
            ],
        ];

        User::insert($users);
    }
}
